[package]
name = "chimera-hybrid-swap"
version = "0.1.0"
edition = "2021"

[dependencies]
arch_program = "0.5.2"
borsh = { version = "1.5.1", features = ["derive"] }
bitcoin = { version = "0.31.0", features = ["serde"] }
hex = "0.4.3"

[lib]
crate-type = ["cdylib"]
