import { Inter } from "next/font/google";
import { motion, AnimatePresence } from "framer-motion";
import Head from "next/head";
import { useState } from "react";
import WavyBackground from "@/components/WavyBackground";
import Footer from "@/components/Footer";
import Header from "@/components/header";
import Banner from "@/components/Banner";

const inter = Inter({ subsets: ["latin"] });

// FAQ data
const faqData = [
  {
    question: "What is CHIMERA PROTOCOL?",
    answer: "CHIMERA PROTOCOL is a decentralized finance (DeFi) platform built on Bitcoin, leveraging the security and stability of the Bitcoin network while offering modern DeFi capabilities like swapping, liquidity provision, and ETF-like products."
  },
  {
    question: "How does the BTC•TEN•ETF•TOKEN work?",
    answer: "The BTC•TEN•ETF•TOKEN is a tokenized index fund that provides exposure to the top 10 Bitcoin-based assets weighted by market capitalization. It automatically rebalances to maintain target allocations, allowing users to gain diversified exposure to the Bitcoin ecosystem through a single token."
  },
  {
    question: "How do I swap tokens on CHIMERA PROTOCOL?",
    answer: "To swap tokens, navigate to the Swap page, select the tokens you wish to exchange, enter the amount, and click the Swap button. Ensure your wallet is connected and has sufficient balance. The platform will calculate the exchange rate and execute the swap once confirmed."
  },
  {
    question: "What is liquidity provision and how do I earn from it?",
    answer: "Liquidity provision involves depositing pairs of tokens into liquidity pools to facilitate trading. In return, you earn a portion of the trading fees generated by the pool. To provide liquidity, go to the LP page, select a pool, enter the amount of tokens you wish to deposit, and confirm the transaction."
  },
  {
    question: "How are the fees calculated?",
    answer: "Fees are calculated as a percentage of the transaction volume. For swaps, there is a 1% fee, of which 0.8% goes to liquidity providers and 0.2% to the protocol treasury. For ETF operations, there is a 0.5% management fee annually, plus a 0.1% fee for minting or redeeming tokens."
  },
  {
    question: "Is CHIMERA PROTOCOL secure?",
    answer: "CHIMERA PROTOCOL prioritizes security through multiple layers of protection. All smart contracts have undergone thorough audits by independent security firms. The protocol uses Bitcoin's security model and implements additional safeguards to protect user funds and ensure transaction integrity."
  },
  {
    question: "What wallets are supported?",
    answer: "CHIMERA PROTOCOL supports major Bitcoin wallets including Xverse, Unisat, and Leather. These wallets allow you to interact with the protocol securely while maintaining control of your private keys."
  },
  {
    question: "How is the ETF rebalanced?",
    answer: "The BTC•TEN•ETF•TOKEN is rebalanced weekly to maintain the target allocations based on market capitalization. The rebalancing process is automated and transparent, with all transactions visible on the blockchain. This ensures the ETF accurately represents the current state of the top Bitcoin assets."
  },
  {
    question: "What happens if I redeem my ETF tokens?",
    answer: "When you redeem your BTC•TEN•ETF•TOKEN, you receive the underlying assets in proportion to their current weights in the ETF. The redemption process is subject to a small fee, and the tokens you receive will be sent directly to your connected wallet."
  },
  {
    question: "Where can I get technical support?",
    answer: "For technical support, you can join our Discord community where our team and community members are available to help. You can also reach out via Twitter or submit a support ticket through our website. We aim to respond to all inquiries within 24 hours."
  }
];

export default function FAQPage() {
  const [openIndex, setOpenIndex] = useState<number | null>(null);

  const toggleAccordion = (index: number) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  return (
    <div className="overflow-hidden">
      <Banner />
      <main
        className={`flex min-h-screen flex-col items-center ${inter.className} overflow-y-auto`}
      >
        <Head>
          <title>CHIMERA PROTOCOL - FAQ</title>
          <link rel="icon" href="/chimera-icon.svg" />
        </Head>

        {/* Content Container with Vignette */}
        <div className="relative w-full min-h-screen flex flex-col">
          {/* Fixed Wavy Background that stays throughout the page */}
          <div className="fixed inset-0 w-full h-full">
            <WavyBackground className="w-full h-full" />
            <div className="absolute inset-0 bg-black opacity-50" />
          </div>

          {/* Content */}
          <div className="relative z-10 flex-1 flex flex-col">
            <Header
              connectWallet={() => {}}
              selectWalletConnect={() => {}}
              paymentAddress=""
              setPaymentAddress={() => {}}
              ordinalAddress=""
              setOrdinalAddress={() => {}}
              paymentPubkey=""
              setPaymentPubkey={() => {}}
              ordinalPubkey=""
              setOrdinalPubkey={() => {}}
              walletType=""
              setWalletType={() => {}}
              openWalletModal={false}
              setOpenWalletModal={() => {}}
            />

            {/* FAQ Content */}
            <div className="flex-1 flex items-start justify-center px-4 py-8 mt-16">
              <div className="w-full max-w-[800px] flex flex-col gap-6 pb-8">
                <motion.div
                  className="w-full"
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.5 }}
                >
                  {/* FAQ Header */}
                  <div className="bg-black/60 backdrop-blur-md rounded-2xl overflow-hidden border border-white/[0.1] p-6 mb-6">
                    <h1 className="text-3xl font-bold text-white mb-2">Frequently Asked Questions</h1>
                    <p className="text-gray-300">Find answers to common questions about CHIMERA PROTOCOL, our services, and how to use the platform.</p>
                  </div>
                  
                  {/* FAQ Accordion */}
                  <div className="bg-black/60 backdrop-blur-md rounded-2xl overflow-hidden border border-white/[0.1] p-6">
                    {faqData.map((faq, index) => (
                      <div key={index} className="mb-4 last:mb-0">
                        <button
                          onClick={() => toggleAccordion(index)}
                          className={`w-full flex justify-between items-center p-4 rounded-lg text-left transition-colors ${
                            openIndex === index
                              ? "bg-gradient-to-r from-orange-500/20 to-red-500/20 border border-orange-500/30"
                              : "bg-black/40 hover:bg-black/50 border border-white/10"
                          }`}
                        >
                          <span className="text-white font-medium">{faq.question}</span>
                          <svg
                            xmlns="http://www.w3.org/2000/svg"
                            width="20"
                            height="20"
                            viewBox="0 0 24 24"
                            fill="none"
                            stroke="currentColor"
                            strokeWidth="2"
                            strokeLinecap="round"
                            strokeLinejoin="round"
                            className={`text-white transition-transform duration-200 ${
                              openIndex === index ? "rotate-180" : ""
                            }`}
                          >
                            <polyline points="6 9 12 15 18 9"></polyline>
                          </svg>
                        </button>
                        <AnimatePresence>
                          {openIndex === index && (
                            <motion.div
                              initial={{ height: 0, opacity: 0 }}
                              animate={{ height: "auto", opacity: 1 }}
                              exit={{ height: 0, opacity: 0 }}
                              transition={{ duration: 0.2 }}
                              className="overflow-hidden"
                            >
                              <div className="p-4 bg-black/20 border-x border-b border-white/10 rounded-b-lg">
                                <p className="text-gray-300">{faq.answer}</p>
                              </div>
                            </motion.div>
                          )}
                        </AnimatePresence>
                      </div>
                    ))}
                  </div>
                  
                  {/* Additional Support Section */}
                  <div className="bg-black/60 backdrop-blur-md rounded-2xl overflow-hidden border border-white/[0.1] p-6 mt-6">
                    <h2 className="text-xl font-bold text-white mb-4">Need More Help?</h2>
                    <p className="text-gray-300 mb-4">
                      If you couldn't find the answer to your question, feel free to reach out to our community or support team.
                    </p>
                    <div className="flex flex-wrap gap-4">
                      <a
                        href="https://discord.gg/chimeraprotocol"
                        target="_blank"
                        rel="noopener noreferrer"
                        className="px-4 py-2 bg-[#5865F2]/20 text-[#5865F2] rounded-lg hover:bg-[#5865F2]/30 transition flex items-center"
                      >
                        <svg className="w-5 h-5 mr-2" fill="currentColor" viewBox="0 0 24 24">
                          <path d="M20.317 4.3698a19.7913 19.7913 0 00-4.8851-1.5152.0741.0741 0 00-.0785.0371c-.211.3753-.4447.8648-.6083 1.2495-1.8447-.2762-3.68-.2762-5.4868 0-.1636-.3847-.4058-.8742-.6177-1.2495a.077.077 0 00-.0785-.037 19.7363 19.7363 0 00-4.8852 1.515.0699.0699 0 00-.0321.0277C.5334 9.0458-.319 13.5799.0992 18.0578a.0824.0824 0 00.0312.0561c2.0528 1.5076 4.0413 2.4228 5.9929 3.0294a.0777.0777 0 00.0842-.0276c.4616-.6304.8731-1.2952 1.226-1.9942a.076.076 0 00-.0416-.1057c-.6528-.2476-1.2743-.5495-1.8722-.8923a.077.077 0 01-.0076-.1277c.1258-.0943.2517-.1923.3718-.2914a.0743.0743 0 01.0776-.0105c3.9278 1.7933 8.18 1.7933 12.0614 0a.0739.0739 0 01.0785.0095c.1202.099.246.1981.3728.2924a.077.077 0 01-.0066.1276 12.2986 12.2986 0 01-1.873.8914.0766.0766 0 00-.0407.1067c.3604.698.7719 1.3628 1.225 1.9932a.076.076 0 00.0842.0286c1.961-.6067 3.9495-1.5219 6.0023-3.0294a.077.077 0 00.0313-.0552c.5004-5.177-.8382-9.6739-3.5485-13.6604a.061.061 0 00-.0312-.0286zM8.02 15.3312c-1.1825 0-2.1569-1.0857-2.1569-2.419 0-1.3332.9555-2.4189 2.157-2.4189 1.2108 0 2.1757 1.0952 2.1568 2.419 0 1.3332-.9555 2.4189-2.1569 2.4189zm7.9748 0c-1.1825 0-2.1569-1.0857-2.1569-2.419 0-1.3332.9554-2.4189 2.1569-2.4189 1.2108 0 2.1757 1.0952 2.1568 2.419 0 1.3332-.946 2.4189-2.1568 2.4189Z" />
                        </svg>
                        Join Discord
                      </a>
                      <a
                        href="https://twitter.com/chimeraprotocol"
                        target="_blank"
                        rel="noopener noreferrer"
                        className="px-4 py-2 bg-[#1DA1F2]/20 text-[#1DA1F2] rounded-lg hover:bg-[#1DA1F2]/30 transition flex items-center"
                      >
                        <svg className="w-5 h-5 mr-2" fill="currentColor" viewBox="0 0 24 24">
                          <path d="M23.953 4.57a10 10 0 01-2.825.775 4.958 4.958 0 002.163-2.723c-.951.555-2.005.959-3.127 1.184a4.92 4.92 0 00-8.384 4.482C7.69 8.095 4.067 6.13 1.64 3.162a4.822 4.822 0 00-.666 2.475c0 1.71.87 3.213 2.188 4.096a4.904 4.904 0 01-2.228-.616v.06a4.923 4.923 0 003.946 4.827 4.996 4.996 0 01-2.212.085 4.936 4.936 0 004.604 3.417 9.867 9.867 0 01-6.102 2.105c-.39 0-.779-.023-1.17-.067a13.995 13.995 0 007.557 2.209c9.053 0 13.998-7.496 13.998-13.985 0-.21 0-.42-.015-.63A9.935 9.935 0 0024 4.59z" />
                        </svg>
                        Follow Twitter
                      </a>
                      <a
                        href="mailto:support@chimeraprotocol.com"
                        className="px-4 py-2 bg-white/10 text-white rounded-lg hover:bg-white/20 transition flex items-center"
                      >
                        <svg className="w-5 h-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
                        </svg>
                        Email Support
                      </a>
                    </div>
                  </div>
                </motion.div>
              </div>
            </div>
          </div>
          <Footer />
        </div>
      </main>
    </div>
  );
} 